"""Initial schema - all models

Revision ID: 0d399bab58f6
Revises: 
Create Date: 2026-01-13 17:00:50.299168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d399bab58f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_lek', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('savings', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_tier_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('badge_color', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agent_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('bio_en', sa.String(), nullable=True),
    sa.Column('license_document_url', sa.String(), nullable=True),
    sa.Column('company_document_url', sa.String(), nullable=True),
    sa.Column('id_document_url', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('listings_count', sa.Integer(), nullable=False),
    sa.Column('deals_completed', sa.Integer(), nullable=False),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('buyer_demands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('budget_min_eur', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_max_eur', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_min_lek', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('budget_max_lek', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('preferred_city_en', sa.String(), nullable=False),
    sa.Column('preferred_area', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('demand_type', sa.String(), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_demands_assigned_agent_id'), 'buyer_demands', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_buyer_demands_buyer_id'), 'buyer_demands', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_demands_category'), 'buyer_demands', ['category'], unique=False)
    op.create_index(op.f('ix_buyer_demands_created_at'), 'buyer_demands', ['created_at'], unique=False)
    op.create_index(op.f('ix_buyer_demands_preferred_city_en'), 'buyer_demands', ['preferred_city_en'], unique=False)
    op.create_index(op.f('ix_buyer_demands_status'), 'buyer_demands', ['status'], unique=False)
    op.create_table('buyer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('promotion_tier', sa.String(), nullable=False),
    sa.Column('promotion_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promotion_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_title_en', sa.String(), nullable=False),
    sa.Column('public_description_en', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('public_location_city_en', sa.String(), nullable=False),
    sa.Column('public_location_area', sa.String(), nullable=True),
    sa.Column('real_business_name', sa.String(), nullable=True),
    sa.Column('real_location_address', sa.String(), nullable=True),
    sa.Column('real_location_lat', sa.Float(), nullable=True),
    sa.Column('real_location_lng', sa.Float(), nullable=True),
    sa.Column('real_description_en', sa.String(), nullable=True),
    sa.Column('asking_price_eur', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('asking_price_lek', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monthly_revenue_eur', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_revenue_lek', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('roi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('years_in_operation', sa.Integer(), nullable=True),
    sa.Column('is_physically_verified', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_agent_id'), 'listings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_listings_asking_price_eur'), 'listings', ['asking_price_eur'], unique=False)
    op.create_index(op.f('ix_listings_category'), 'listings', ['category'], unique=False)
    op.create_index(op.f('ix_listings_created_at'), 'listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_listings_is_physically_verified'), 'listings', ['is_physically_verified'], unique=False)
    op.create_index(op.f('ix_listings_monthly_revenue_eur'), 'listings', ['monthly_revenue_eur'], unique=False)
    op.create_index(op.f('ix_listings_promotion_tier'), 'listings', ['promotion_tier'], unique=False)
    op.create_index(op.f('ix_listings_public_location_city_en'), 'listings', ['public_location_city_en'], unique=False)
    op.create_index(op.f('ix_listings_roi'), 'listings', ['roi'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('promotion_id', sa.UUID(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_agent_id'), 'credit_transactions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_listing_id'), 'credit_transactions', ['listing_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_type'), 'credit_transactions', ['type'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'listing_id', 'interaction_type', name='uq_lead_buyer_listing_type')
    )
    op.create_index(op.f('ix_leads_agent_id'), 'leads', ['agent_id'], unique=False)
    op.create_index(op.f('ix_leads_buyer_id'), 'leads', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_listing_id'), 'leads', ['listing_id'], unique=False)
    op.create_table('listing_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_images_listing_id'), 'listing_images', ['listing_id'], unique=False)
    op.create_table('promotion_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('views_during_promotion', sa.Integer(), nullable=False),
    sa.Column('leads_during_promotion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_history_end_date'), 'promotion_history', ['end_date'], unique=False)
    op.create_index(op.f('ix_promotion_history_listing_id'), 'promotion_history', ['listing_id'], unique=False)
    op.create_index(op.f('ix_promotion_history_start_date'), 'promotion_history', ['start_date'], unique=False)
    op.create_index(op.f('ix_promotion_history_status'), 'promotion_history', ['status'], unique=False)
    op.create_table('saved_listings',
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('buyer_id', 'listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_listings')
    op.drop_index(op.f('ix_promotion_history_status'), table_name='promotion_history')
    op.drop_index(op.f('ix_promotion_history_start_date'), table_name='promotion_history')
    op.drop_index(op.f('ix_promotion_history_listing_id'), table_name='promotion_history')
    op.drop_index(op.f('ix_promotion_history_end_date'), table_name='promotion_history')
    op.drop_table('promotion_history')
    op.drop_index(op.f('ix_listing_images_listing_id'), table_name='listing_images')
    op.drop_table('listing_images')
    op.drop_index(op.f('ix_leads_listing_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_buyer_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_agent_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_credit_transactions_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_listing_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_agent_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_roi'), table_name='listings')
    op.drop_index(op.f('ix_listings_public_location_city_en'), table_name='listings')
    op.drop_index(op.f('ix_listings_promotion_tier'), table_name='listings')
    op.drop_index(op.f('ix_listings_monthly_revenue_eur'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_physically_verified'), table_name='listings')
    op.drop_index(op.f('ix_listings_created_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_category'), table_name='listings')
    op.drop_index(op.f('ix_listings_asking_price_eur'), table_name='listings')
    op.drop_index(op.f('ix_listings_agent_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('email_verification_tokens')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_buyer_demands_status'), table_name='buyer_demands')
    op.drop_index(op.f('ix_buyer_demands_preferred_city_en'), table_name='buyer_demands')
    op.drop_index(op.f('ix_buyer_demands_created_at'), table_name='buyer_demands')
    op.drop_index(op.f('ix_buyer_demands_category'), table_name='buyer_demands')
    op.drop_index(op.f('ix_buyer_demands_buyer_id'), table_name='buyer_demands')
    op.drop_index(op.f('ix_buyer_demands_assigned_agent_id'), table_name='buyer_demands')
    op.drop_table('buyer_demands')
    op.drop_table('agent_profiles')
    op.drop_table('users')
    op.drop_table('promotion_tier_configs')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
